<!DOCTYPE html>
<html>
<head>
	<title>Users</title>
</head>
<body>
	<h1>Users</h1>
	<p>Here is the list of users</p>

	<table border="1">
		<thead>
			<tr>
				<th>Username</th>
				<th>Email</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($users as $user) { ?>
			<tr>
				<td><?= $user->username ?></td>
				<td><?= $user->email ?></td>
				<td>
					<a href="/users/edit?id=<?= $user->id ?>">update</a>
					<a href="/users/delete?id=<?= $user->id ?>">delete</a>
				</td>
			</tr>
			<?php } ?>
		</tbody>
	</table>

	<p><a href="/users/add">New user</a></p>
	<p><a href="/home">Home</a></p>
</body>
</html>